# This file is generated by Anlogic Timing Wizard. 23 05 2019

#Created Clock
create_clock -name clk -period 41.667 [get_ports {clk}]

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

#Set False Path
set_false_path  -from [get_clocks {clk}] -to [get_clocks {pl0/pll_inst.clkc[0]}]
set_false_path  -from [get_clocks {pl0/pll_inst.clkc[0]}] -to [get_clocks {clk}]
